### ISSUE TITLE
useIdentity expect a hash instead of an identity

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/Scatter#10]
An idea could be either pass the identity object or name it useIdentityHash? 

```
scatter.useIdentity(identity.hash);
````

**Comment by nsjames** [comment]
I agree, the naming convention is confusing. 
I think the best option would be allowing either a hash or an object to be passed ( the reason for the latter would be perhaps applications want to save identity hashes locally without having to save the entire object, and the hash would be the only thing taken from the identity anyway )

I'll change it so be either
`scatter.useIdentity(identity:object)`
or
`scatter.useIdentity(hash:string)`

**Comment by nsjames** [comment]
fd49116eab207db185c324281abf20b8ebf0d5b3
