### ISSUE TITLE
ETH private keys with `0x` prefix are not seen as valid ETH private key

### ISSUE THREAD

**Issue by rterbush** [EOSEssentials/Scatter#105]
This issue is biting many people that are trying to generate fallback keys coming from hardware wallets such as Ledger.

`bip39` and other private key recovery tools are providing the ETH private key with a `0x` prefix. Scatter refuses to convert this ETH private key to an EOS keypair if it is provided an ETH private key using this format.

Principle of Robustness would suggest that to be more liberal about what Scatter accepts, ignoring a `0x` prefix on these keys, would cause a lot less confusion and support requests.

https://en.wikipedia.org/wiki/Robustness_principle

**Comment by nsjames** [comment]
c2d476adeb2af107c35fd331d627be8a87329901
