### ISSUE TITLE
Browser Support : Firefox for Android 

### ISSUE THREAD

**Issue by friedger** [EOSEssentials/Scatter#106]
Pop-ups don't work (yet?) on Firefox for Android.
Please add a pending transaction page to the extension such that the user can switch manually between dapp and scatter. Similar to metamask.

**Comment by nsjames** [comment]
This is **really** not meant for firefox mobile. 
There will be a separate native version of Scatter for mobile phones.

**Comment by friedger** [comment]
This means progressive web apps (PWAs) needs to maintain two versions of their dapp? Look at monstereos.io, how do you envision that they integrate with the native version of scatter? Will you provide a javascript bridge?

Or do you expect a Web API for identification and for transactions like the Web Payment API?

**Comment by friedger** [comment]
Would the Web Authentication API work for EOS? https://w3c.github.io/webauthn

**Comment by nsjames** [comment]
That's a very good question. 
I suppose for **web** apps it should happen behind the scenes and work the same way it does on desktop so that their development process isn't segregated by device specifics.

**Comment by nsjames** [comment]
However, the native mobile implementation won't be solely for web apps, but also native mobile apps like games.
