### ISSUE TITLE
EOS balance displayed incorrectly when using multiple accounts

### ISSUE THREAD

**Issue by Soleone** [EOSEssentials/Scatter#108]
Looks like there is a bug right now fetching the EOS balance.

I have two different identities with two different EOS accounts. When I press the circle button it shows the same balance in both EOS accounts, but one is inaccurate:

![image](https://user-images.githubusercontent.com/2923/41559683-c3754698-7312-11e8-82c8-771d0cf97511.png)

It should be showing 0 there for the second account's balance.

**Comment by nsjames** [comment]
6f3e86e1b65470e617f1fa26d0ecae99d5d5fb5a
