### ISSUE TITLE
Avoid closing UI when browser looses focus

### ISSUE THREAD

**Issue by athei** [EOSEssentials/Scatter#113]
At least on macOS and Firefox the UI closes when the browser looses focus. This is problematic for copy & paste. Importing a key pair is flat out impossible because you cannot have both at the same time in your clip board. When you change focus the UI closes and the things you copied in are gone.

**Comment by nsjames** [comment]
Sorry bud, impossible to fix. That's browser controlled and not something we can modify. 
Soon Scatter will have a desktop companion which will allow for things not to close.
