### ISSUE TITLE
Clarify use of proprietary code

### ISSUE THREAD

**Issue by jeremi** [EOSEssentials/Scatter#16]
Reading the doc and looking at the dependencies of this project, it seems it is using some proprietary code [Extension-Streams](https://github.com/nsjames/Extension-Streams).
As there are no details on the license of this dependency, it is a legal liability for any user of this project.
Could we either clarify the license of this dependency or replace it?

**Comment by nsjames** [comment]
Hey man, didn't even notice that. Thanks for bringing it to our attention. I went ahead and added an MIT license to that project as well.

**Comment by jeremi** [comment]
Awesome, thanks @nsjames !
