### ISSUE TITLE
Creating First Identity Screen no scrollbar

### ISSUE THREAD

**Issue by leordev** [EOSEssentials/Scatter#2]
OS: OSX High Sierra 10.13.3
Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
Situation: Inside the "creating first identity" screen (see below) I can't see the submit button and there's no scrollbar.

![image](https://user-images.githubusercontent.com/6147142/35782336-582bee1c-09c4-11e8-822c-ef4fb80bdd08.png)

**Comment by nsjames** [comment]
Fixed with dynamic height in latest push
