### ISSUE TITLE
binaryen option not supported for setcode operation

### ISSUE THREAD

**Issue by bbreuil** [EOSEssentials/Scatter#26]
The binaryen option is required by eosjs for the setcode operation and it appears that this option cannot be passed to the Scatter eos instance due to the way options are stringified.

This seems to be the line of code causing the issue in the EOS plugin class:

`
_eos(Object.assign(JSON.stringify(_options), {httpEndpoint, signProvider}))[method](...args)
`

**Comment by bbreuil** [comment]
Thanks for the quick reply.

The use case is to be able to upload code/abi via the browser.

I verified that removing the stringify does fix the issue.

**Comment by nsjames** [comment]
Alrighty, I'll run some checks and see if it can be omitted safely, if not I'll find a way to make this work.

**Comment by nsjames** [comment]
I don't see any issues with this. 1288dd8ca8cbf59bd13b6a82b8c423a5aef21102
