### ISSUE TITLE
Adding Language: chinese

### ISSUE THREAD

**Issue by oscnet** [EOSEssentials/Scatter#41]
I 'm from ZWZM, one of the best Chinese blockchain translating community which is dedicated to translating valuable blockchain books and articles into Chinese. Some top Chinese blockchain leaders and evangelists ,such as James Gong , Dr. Bin Lu etc. are our community advisors.

I 'd like to translate it into Chinese

**Comment by nsjames** [comment]
Happy to have you, go for it. <3
