### ISSUE TITLE
Extension locks up when trying to connect to Jungle Testnet

### ISSUE THREAD

**Issue by mlockett42** [EOSEssentials/Scatter#47]
Create a key pair in Scatter.
Go to identities, I already have identities which are not linked to any key
Open one of the identities to edit and go to the account section
Choose EOS:159.65.161.248:8888 as the network under account
Choose the key pair you just create
Click Import
Get an error message 'No account found'
This is the error behaviour

Choose EOS:dev.cryptolions.io:8888 as the network under account
Choose the same key pair as before
Click Import
Nothing happens - the import button greys out but not error message stays in that state forever.
Obviously incorrect behaviour

I am able to reproduce the same behaviour running my own private testnet, build from dawn4 source code

**Comment by nsjames** [comment]
`eosjs` just pushed a dawn4 compatible build which I am integrating as we speak. This should solve this issue.

**Comment by mlockett42** [comment]
@nsjames suggestion fixed this. Dawn version between the testnet and local client was different
