### ISSUE TITLE
Can I send transactions without requirement of identity?

### ISSUE THREAD

**Issue by ceeji** [EOSEssentials/Scatter#50]
I know identity is convenient in some situations, but sometimes i just want to send a transaction. So some questions:

1. Why Scatter introduced the concept of Identity? Can I send transactions whihout requirement of identity? 
2. The identity is created for users who have more than one account or have accounts on different chains, right?

**Comment by nsjames** [comment]
The Identities were actually born out of a security measure. Without identities Scatter would have to give the website free information ( the way that MetaMask does, where it gives you the account before asking for it )

With Scatter you must request to use a user's Identity, and that's how you get the blockchain account to use for them ( account for EOS , address for ethereum )

Every use has at least 1 identity. When they first install Scatter they are given one that they need to fill with blockchain accounts.
