### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by yepp4you** [EOSEssentials/Scatter#51]
We need to support https for security, so we hope to get support soon.

**Comment by nsjames** [comment]
Ah yes. 
This is still lingering from the time that `nodeos` had issues with SSL. 
I'll add support for this in one of the next updates.

**Comment by nsjames** [comment]
@yepp4you where did something actually hinder you from using https?

**Comment by yepp4you** [comment]
When registering network in scatter, only domain or IP could be registered, so we could not register https protocol. Our web page will use https, which will cause problems if you make a call to http on the https page, because the chrome browser will not allow the call.
If you have any way to register your network with https, please let me know.

**Comment by nsjames** [comment]
aabec887783fedb1f5dfc2a9bfef094494433db5
