### ISSUE TITLE
Load from Backup not closing after selecting file

### ISSUE THREAD

**Issue by cuducos** [EOSEssentials/Scatter#63]
Hi : )

I was using Scatter in Chrome and now I'm trying it on Firefox. I exported by backup in Chrome and it successfully generated my `.keychain` file.

However, on Firefox, when I click _Load from Backup_, then _Select File_, then actually select the `.keychain` file and click _Open_, Scatter windows closes and no import is successful. I don't even get the chance to click _Import Keychain_…

I'm using Firefox 60.0.1, with Scatter 4.0.3 (on both browsers) and macOS 10.13.4.

**Comment by nsjames** [comment]
https://github.com/EOSEssentials/Scatter/issues/93
