### ISSUE TITLE
Account not being saved/attached to Identity

### ISSUE THREAD

**Issue by cuducos** [EOSEssentials/Scatter#64]
Dear,

I'm trying to attach a new account to a identity (tested with a new one and editing an existing one). On the identity screen, I can select the network and the account, then I click _Import_ and next _Save_. However no account is actually saved/attached to the identity.

I'm using Firefox 60.0.1, with Scatter 4.0.3 (on Chrome and Firefox) and macOS 10.13.4.

No error is displayed. Any clue abouy what I might be doing wrong?

**Comment by nsjames** [comment]
Does it pop up the prompt to select the account@permission based on the keypair?

**Comment by cuducos** [comment]
No error message, no pop up to select the account either.

**Comment by nsjames** [comment]
Where is the account registered ( network )?

**Comment by cuducos** [comment]
Hi @nsjames – we were testing in our dev network, and we just found out a bug in that particular account. Sorry about that.
