### ISSUE TITLE
EOS networks don't support HTTPS endpoints

### ISSUE THREAD

**Issue by k26dr** [EOSEssentials/Scatter#65]
Eosjs requests routed through Scatter do not support HTTPS. The httpEndpoint config option is automatically prefixed with `http://`

https://github.com/EOSEssentials/Scatter/blob/27316e762fb03ef35267daa07a0ac08f40aa443b/src/plugins/defaults/eos.js#L44

Using an HTTPS endpoint would require supporting a `protocol` option for networks so it could be used like:

```js
var network = {
    blockchain: 'eos',
    protocol: "https",
    host: "bp.libertyblock.io",
    port: 8890,
    chainId: "a628a5a6123d6ed60242560f23354c557f4a02826e223bb38aad79ddeb9afbca"
}
```

**Comment by yepp4you** [comment]
I have already registered below.
https://github.com/EOSEssentials/Scatter/issues/51

**Comment by k26dr** [comment]
I'll look into this. Issue seems to be on our end.

**Comment by k26dr** [comment]
Duplicate issue. Closing

**Comment by k26dr** [comment]
![image](https://user-images.githubusercontent.com/7109698/40783481-5fd792dc-6497-11e8-82fe-fc9e543de1e4.png)

Server is working fine.

**Comment by k26dr** [comment]
https://github.com/LibertyBlock/eos-voting/blob/master/main.js#L51

That's an example of how to connect. Replace URL with your desired one. HTTPS is supported by eosjs. I have used it before.

**Comment by nsjames** [comment]
aabec887783fedb1f5dfc2a9bfef094494433db5
