### ISSUE TITLE
Network in port 81

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/Scatter#7]
My network is in port 81, perhaps Scatter should allow to host the network in any port.

<img width="351" alt="screen shot 2018-02-16 at 15 57 59" src="https://user-images.githubusercontent.com/1288106/36313584-3eda509e-1332-11e8-857a-b2763937273f.png">

**Comment by nsjames** [comment]
You're right, it's probably not the best idea to constrict the ports like that. It was done as an (unnecessary) precaution against reserved ports but the operating system eosd is running on will handle that anyway so there's really no point in disallowing it from Scatter.

**Comment by nsjames** [comment]
a21529b9569865a03548c4c6816fbc310080218f
