### ISSUE TITLE
need better fonts

### ISSUE THREAD

**Issue by bitcoiners** [EOSEssentials/Scatter#86]
Scatter is incredibly hard to use. Fonts are small and semi-transparent and hard to read. 
![image](https://user-images.githubusercontent.com/38520/41320396-d3161214-6ec9-11e8-987b-fa244db3f76b.png)

**Comment by nsjames** [comment]
Fonts have been darkened 271a6843238e0cbd8c7a60921863731e1ef2c1fb

**Comment by bitcoiners** [comment]
Problem is not resoved.

![image](https://user-images.githubusercontent.com/38520/41564228-5be210a0-737c-11e8-9b91-56d3c3a00628.png)

Fonts are too small and semi-transparent. Nearly impossible to read instructions in tiny font.
Also, there is a scrolling problem where scatter window does not resize properly and part of the screen is not accessible.

**Comment by nsjames** [comment]
darkened fonts, set domain to blue, enlarged description font from 9px to 13px.

632f1d8fe07657c7d18eaf4fff369a1edb4189be

**Comment by bitcoiners** [comment]
Instruction fonts are still to small and hard to read. Please increase font size and darken.

![image](https://user-images.githubusercontent.com/38520/41758804-32a401b2-7615-11e8-9681-4059575cda31.png)

**Comment by nsjames** [comment]
![image](https://user-images.githubusercontent.com/10360675/41759999-0936dae0-75fa-11e8-8cfa-49d0e58e929a.png)

**Comment by nsjames** [comment]
Seems to still be a little smaller on yours, must still be cached. 
However, that's as big as they can get without overflowing outside of the window ( there's also multiple languages to deal with there )

Perhaps the text just needs to be simpler, so that it can become larger.

**Comment by bitcoiners** [comment]
I am using a laptop with a 13' screen, maybe that is why my fonts appear smaller.
