### ISSUE TITLE
Can't access a Confluence wiki when Scatter is activated

### ISSUE THREAD

**Issue by CPUFronz** [EOSEssentials/Scatter#89]
When I try to access a (private) confluence wiki page, the wiki doesn't load  and the console shows the following error message:
```
index.js:10 Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (index.js:10)
    at Object.LTS4 (index.js:27)
    at i (bootstrap:61)
    at Object.4 (runtime.js:726)
    at i (bootstrap:61)
    at +/o8 (bootstrap:178)
    at bootstrap:178
```

This error happens in Chrome and Firefox. So far the only workaround is to deactivate Scatter.

**Comment by nsjames** [comment]
9c3b0877b21dd94efc9725b019bc0fec35a9c93f
