### ISSUE TITLE
Identity request showing and accepting disabled identities

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/Scatter#9]
That identity was disabled, perhaps we shouldnt allow to use it / show it as a possible option? 

<img width="676" alt="screen shot 2018-02-16 at 16 14 11" src="https://user-images.githubusercontent.com/1288106/36314238-7f688ec6-1334-11e8-9e02-6e0e0c11c0c7.png">

**Comment by nsjames** [comment]
Oh damn, forgot about that. Yeah that definitely shouldn't be selectable. I guess it would still be good to show on the list though just to remind users that they might have temporarily disabled the Identity they are trying to use.

**Comment by nsjames** [comment]
eaed093481646db1aab9f2806da2750c48b7a8ec
