### ISSUE TITLE
Responsible Disclosure and Bug Bounties

### ISSUE THREAD

**Issue by jamespic** [EOSEssentials/Scatter#90]
I am investigating the security of Scatter. I could not see any info on the home page for the correct procedure for reporting security vulnerabilities. Could you clarify:
- What is the correct way to responsibly disclose potential security issues?
- Are there any bounties available for disclosing security issues?

**Comment by nsjames** [comment]
Hey man, thanks for the suggestion. I went ahead and added a section about this on the readme. <3

https://github.com/EOSEssentials/Scatter#responsible-disclosure-and-bug-bounties
