### ISSUE TITLE
'Load From Backup' Doesn't Work.

### ISSUE THREAD

**Issue by Aphiso** [EOSEssentials/Scatter#93]
While using both Chrome and Firefox on Linux, when I click load from backup it opens up the window asking me to select the wallet, but when that happens scatter closes. Even after selecting the wallet and clicking Scatter again it just returns you to the Create a Wallet or Load a Wallet screen.

IS there a workaround or a fix coming soon for this?

**Comment by nsjames** [comment]
You can right click Scatter and hit inspect which will force the popup to stay open. 
That whole flow is going to be replaced with a `textarea` soon because it's annoying and a bad UX. Sorry for the hassle, nothing I can do about built-in browser functionality like that.

**Comment by Aphiso** [comment]
Is that for Chrome only I'm assuming? Don't see Inspect available on FF.
