### ISSUE TITLE
How to properly suggest networks?

### ISSUE THREAD

**Issue by kasperfish** [EOSEssentials/Scatter#95]
Scatter is buggy when I change the network settings in my code and refresh. No popup to select the identity.
so switching between the testnetwork and mainnet is not possible without reinstalling scatter. I'm doing something wrong probably. If I suggest a network and scatter has no linked identity with that network (which is obviously normal since I suggest a new network), I receive a popup from scatter telling me this. However If I then link my key to the new suggested network and select an account scatter doesn't give me a popup anymore to select the account linked with the identity. I have to reinstall scatter to make it work again. 
When I manually add the networks in scatter everything works fine. 

This error comes up in the console, however I didn't reject anything since there was no popup.
![image](https://user-images.githubusercontent.com/5130772/41460188-183d1590-708c-11e8-8582-44fc199a0067.png)

![image](https://user-images.githubusercontent.com/5130772/41460279-73e67828-708c-11e8-86c0-48ece7e85d25.png)

**Comment by nsjames** [comment]
Are you sure you don't have a Scatter popup lingering in the background?
It's hard to tell what's actually happening here from just the code ( which looks fine btw )

**Comment by kasperfish** [comment]
do you mean something like this?
![image](https://user-images.githubusercontent.com/5130772/41497964-5be65826-7161-11e8-8468-98e0b7157208.png)

**Comment by kasperfish** [comment]
seems like both issues are related after all...

**Comment by nsjames** [comment]
Yeah absolutely. That would restrict Scatter from creating another popup. 
I've just pushed a fix which will focus the last open popup.

2ad83f9974cf3901b0c24e94800d2741fae1d2ad
