### ISSUE TITLE
unrecoverable bug: need to reinstall scatter

### ISSUE THREAD

**Issue by kasperfish** [EOSEssentials/Scatter#98]
How to reproduce this bug: unfocus the transaction confirmation popup (or any other popup), click new transaction button in gui (or trigger scatter to popup an other window)
![image](https://user-images.githubusercontent.com/5130772/41497964-5be65826-7161-11e8-8468-98e0b7157208.png)
this happens when you unfocus a popup and then click a button in the GUI for a new transaction. Once you encountered a window like this you need to reinstall Scatter since no other popups will display after this window (browser restart, system reboot does not help) as an example when I lock Scatter and visit my app again I get this... without popup.
![image](https://user-images.githubusercontent.com/5130772/41498068-458d5ee6-7164-11e8-9db1-5d19f8a65840.png)
#

**Comment by kasperfish** [comment]
Possible fix is add an eventlistener for unfocus and link it with closing the popup properly. I just noticed that my previous problem was also due to this error. When suggesting a network I did not click "cancel" in one of the popup windows so the window kept existing in the background. When scatter wants to pop up a new window it errors.

**Comment by nsjames** [comment]
This commit focuses the last open popup 2ad83f9974cf3901b0c24e94800d2741fae1d2ad

It should be stated that this is a logical issue which could be restrictive since popups could need to be processed but wont and will be returned to the dapp to be handled as an unrecognizable error.

**Comment by nsjames** [comment]
Also, this only works on Chrome since Firefox can't handle these types of things.

**Comment by nsjames** [comment]
You also don't need to reinstall Scatter. Just find the popup and close it.

**Comment by kasperfish** [comment]
I'm using the chrome browser and there is no popup!
